COMPONENT=TestAMCryptoAppC
CFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
CFLAGS += -I$(TINYOS_OS_DIR)/sensorboards/mts300
# CFLAGS += -I$(TINYOS_OS_DIR)/platforms/shimmer2
# CFLAGS += -I$(TINYOS_OS_DIR)/platforms/ucprotonb
# CFLAGS += -I$(TINYOS_OS_DIR)/chips/atm128/adc
# CFLAGS += -I$(TINYOS_OS_DIR)/chips/atm128rfa1/pins
# CFLAGS += -I$(TINYOS_OS_DIR)/chips/atm1281

TINYOS_ROOT_DIR?=../../..

include $(TINYOS_ROOT_DIR)/Makefile.include
